# Generated by Django 3.1.5 on 2021-01-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(default='', max_length=255, unique=True, verbose_name='Number')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(max_length=250)),
                ('cabin_number', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Washer',
                'verbose_name_plural': 'Washers',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Manager'), (3, 'Washer'), (4, 'Cleaner'), (5, 'Other')], default=3)),
                ('salary', models.IntegerField()),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3)),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='washer.washer')),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_empty', models.BooleanField(default=True)),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin', to='washer.washer')),
            ],
        ),
    ]
