# Generated by Django 3.1.5 on 2021-01-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Van'), (3, 'Other')], default=3)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
        migrations.AddField(
            model_name='carwash',
            name='cabins',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=125, verbose_name='Phone number')),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3)),
                ('percentage', models.FloatField()),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washers', to='washer.carwash')),
            ],
            options={
                'verbose_name': 'Washer',
                'verbose_name_plural': 'Washers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_time', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washer.car')),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='washer.carwash')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='washer.washer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CarWashToType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Sedan'), (2, 'Van'), (3, 'Other')])),
                ('price', models.IntegerField(default=0)),
                ('car_washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carwash_to_car', to='washer.carwash')),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('is_empty', models.BooleanField(default=True)),
                ('car_wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabin', to='washer.carwash')),
            ],
            options={
                'verbose_name': 'Cabin',
                'verbose_name_plural': 'Cabins',
            },
        ),
    ]
