# Generated by Django 3.1.5 on 2021-01-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='washer',
        ),
        migrations.AddField(
            model_name='washer',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='washers', to='washer.Employee'),
        ),
    ]
