# Generated by Django 3.1.5 on 2021-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0002_auto_20210203_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
