# Generated by Django 3.1.5 on 2021-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0003_auto_20210203_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='washer',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='washer',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
