# Generated by Django 3.1.5 on 2021-01-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0004_auto_20210124_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washer',
            name='company_id',
            field=models.CharField(default='', max_length=255, unique=True, verbose_name='Company id'),
        ),
    ]
