# Generated by Django 3.1.5 on 2021-01-24 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0005_auto_20210124_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.CreateModel(
            name='EmployeeToWasher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Manager'), (3, 'Washer'), (4, 'Cleaner'), (5, 'Other')], default=3)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_to_washer', to='washer.employee')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='washer_to_employee', to='washer.washer')),
            ],
        ),
    ]
