# Generated by Django 3.1.5 on 2021-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washer', '0006_auto_20210124_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabin',
            options={'verbose_name': 'Cabin', 'verbose_name_plural': 'Cabins'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='washer',
            name='employee',
        ),
        migrations.AddField(
            model_name='employeetowasher',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
